### ISSUE TITLE
210722 出警记录

### ISSUE THREAD

**Issue by liulangdechouchou** [liulangdechouchou/-#1]
## 活动记录
- 地点：顺昌何缘地 
- 内容：4-6人套餐（一品鲜鱼头、炭火烤肉、蛋炒饭等）
- 参与人：ZS、YXM，HZW，DSC，CJB
- 费用：414元
- 分摊方式：AA，人均82.80
## 警长评价
- 环境不错、服务很周到
- 整体口味偏淡，尤其是蛋炒饭
- 消费较高
## 活动照片
![image](https://user-images.githubusercontent.com/52096966/126762392-e1a51a49-1a21-48e1-acdb-0b57af399320.png)——`photographer：DSC`
## 反馈 & 优化
- 出警提效是一个渐进的过程，如果你有好的建议或者发现的问题，请在评论区留下宝贵的建议

**Comment by zhangsheng1996** [comment]
出警提效建议：
1、丑老师买辆车吧，最好是SUV，不然坐不下（实在不行就让杜思成跑着去吧）
2、到点直接出发，别磨磨唧唧，此处表扬下张生

**Comment by liulangdechouchou** [comment]
> 出警提效建议：
> 1、丑老师买辆车吧，最好是SUV，不然坐不下（实在不行就让杜思成跑着去吧）
> 2、到点直接出发，别磨磨唧唧，此处表扬下张生

好，下次一定
